### Question 4
### The following are logical/theoretical thinking questions. Answer based on your understanding and cannot be used as a reference. The answer can be shortened.
#####################################################################################
# 1.What is Git /SVN (Version Ctrl System)?
# Your Answer:

Git/SVN is powerful version control systems that using for managing and merging code changes. They keep track of change made to the code over time, so if somthing broken, developer can rollback to earlier version. Git uses a distributed model, whereas SVN uses a centralized model.

#####################################################################################
# 2.Explain the purpose of Backend ?
# Your Answer:

Backend developers manage the infrastructure needed to store the data generated by the application and design the interfaces to access. They also can create tools that let other developer work on their projects effenctively by automating processes like code testing.

#####################################################################################
# 3.What is Web Server
# Your Answer:

A web server is a computer that stores web pages and makes them available on the Internet. When someone visits a website, the web server fetches the necessary files and sends them to the visitor's web browser for viewing and interaction.



######################################################################################
# 4.How would you integrate tests into your workflow?
# Your Answer:

Starting integration testing first requires setting the scope of which components or modules must be evaluated. Write tests for individual code units to ensure that they work as expected. Execute the test cases created earlier. Always report and follow up on any issues found during testing. By doing this on a regular basis, you can fix any bugs early and ensure the quality of your work.

######################################################################################
# 5.How would you unit test a new feature?
# Your Answer:

Try to understand what the function is supposed to do. Write small tests to check each part of the function. Make sure to test how the feature interacts with other parts of the programme. Run the tests to see if the feature works as expected. If the test fails, modify the code and the test until it passes.